### ISSUE TITLE
Are the PAM and ASK labels reversed in the wideband dataset?

### ISSUE THREAD

**Issue by slightY** [TorchDSP/torchsig#259]
I have attempted to simulate ASK and PAM signals. I observe that in the time-frequency plot, the ASK signal exhibits a bright line at the carrier frequency, whereas the PAM signal does not show such a phenomenon. Additionally, I have provided labels for instances of the modulation families PAM and ASK from wideband dataset. However, the instances corresponding to the labels are opposite to the results I obtained from my simulations. I would like to seek further confirmation from you regarding this discrepancy.
The results in the wideband dataset are as follows: 
![3d95b829976a5b41a228610a70126b5](https://github.com/user-attachments/assets/ed845fc2-71d9-4102-a82d-a6da98e5f7ec)
![3750a1b424378995dec2a74d5f7a989](https://github.com/user-attachments/assets/d1495402-caa5-4a4b-9b84-a62b70875745)

My simulation results are as follows:
![5399148d4538e0861f9e08628742893](https://github.com/user-attachments/assets/e465b034-19fa-4d1a-9f4c-3b8abfb0bedf)
![4b6e7b1264084c2daa9a29fc6a915ba](https://github.com/user-attachments/assets/ac83e37c-e299-4151-83e4-b6f1b666e36f)

Thank you for your help!

**Comment by MattCarrickPL** [comment]
PAM has a carrier tone and ASK does not due to how the constellations are defined. The PAM has a DC offset, meaning the symbols are all positive, where the symbols for ASK are evenly balanced around zero amplitude and therefore do not have a DC offset. You can see this here in the code: https://github.com/TorchDSP/torchsig/blob/v0.6.0/torchsig/datasets/synthetic.py#L38

The practical value the PAM signal with the large carrier tone is unclear, and we are planning to remove it as part of a larger release planned for sometime in 2025. If you or someone else in the community has reason to keep the PAM signals, please let us know.

Why does your spectrogram contain different labels than the native plot? I don't know, I need more information. My recommendation would be to build off of the code in the examples/ directory which reads and plots the spectrograms with the correct labels. You are also welcome to paste in a portion of your code if you think that would be helpful.

https://github.com/TorchDSP/torchsig/tree/v0.6.0/examples

**Comment by slightY** [comment]
Thank you for your response. After simulation verification, it has been confirmed that the different constellation definitions of ASK and PAM lead to differences in the DC component. Previously, in my simulation process, the constellation definitions for ASK and PAM are opposite to those in the wideband dataset.

**Comment by MattCarrickPL** [comment]
Sounds like your problem has been resolved so I'm closing out this issue. If you have any more problems please let us know.
